settings:
  title: 'Cotpear Status Page'
  url: 'https://status.cotpear.com' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: '所有系統運作良好'
  notAllmonitorsOperational: '部分系統運作有異'
  monitorLabelOperational: '良好'
  monitorLabelNotOperational: '有狀況'
  monitorLabelNoData: '無資料'
  dayInHistogramNoData: '無資料'
  dayInHistogramOperational: '一切良好'
  dayInHistogramNotOperational: ' 個事件' # xx incident(s) recorded

monitors:
  - id: www-cotpear-com # unique identifier
    name: 首頁 - https://www.cotpear.com
    description: 'Cotpear 主頁' # default=empty
    url: 'https://www.cotpear.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: go-cotpear-com # unique identifier
    name: 短連結服務 - go.cotpear.com
    description: '短連結服務(非公用服務)' # default=empty
    url: 'https://go.cotpear.com/' # URL to fetch
    method: GET # default=GET
    expectStatus: 301 # operational status, default=200
    followRedirect: false # should fetch follow redirects, default=false
    
  - id: pwd-cotpear-com
    name: 密碼管理器 - https://pwd.cotpear.com
    description: 'Cotpear 密碼管理器'
    url: 'https://pwd.cotpear.com'
    method: GET
    expectStatus: 200
    
  - id: policies-cotpear-com
    name: Cotpear 隱私權與政策 - https://policies.cotpear.com
    description: 'Cotpear 隱私權與政策'
    url: 'https://policies.cotpear.com'
    method: GET
    expectStatus: 200
    
  - id: yi_chi-cotpear-com
    name: Yi Chi Profile - https://yi-chi.cotpear.com
    description: '關於我 - 齊一個人頁面'
    url: 'https://yi-chi.cotpear.com'
    method: GET
    expectStatus: 200
 
